"""empty message

Revision ID: 14471207a4eb
Revises: 88dea72210b4
Create Date: 2021-07-31 13:00:22.227791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14471207a4eb'
down_revision = '88dea72210b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_category', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_category', 'status')
    # ### end Alembic commands ###
