"""empty message

Revision ID: 3e7060a8ee04
Revises: 3b938c44cffd
Create Date: 2021-07-28 00:03:11.265369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7060a8ee04'
down_revision = '3b938c44cffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_user', sa.Column('is_author', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_user', 'is_author')
    # ### end Alembic commands ###
