"""empty message

Revision ID: 4591799e36ac
Revises: 14471207a4eb
Create Date: 2021-07-31 13:27:42.718494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4591799e36ac'
down_revision = '14471207a4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_category', sa.Column('status', sa.Boolean(), nullable=False))
    op.alter_column('info_category', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_category', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=64),
               nullable=True)
    op.drop_column('info_category', 'status')
    # ### end Alembic commands ###
