"""empty message

Revision ID: 587069022ff9
Revises: 3e7060a8ee04
Create Date: 2021-07-29 20:03:56.104657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '587069022ff9'
down_revision = '3e7060a8ee04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_register_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id_card', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('positive_ID_card_url', sa.String(length=256), nullable=True),
    sa.Column('negative_ID_card_url', sa.String(length=256), nullable=True),
    sa.Column('index_image_url', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['info_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('info_news', sa.Column('collected_counts', sa.Integer(), nullable=True))
    op.alter_column('info_user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('info_user', 'is_author',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_user', 'is_author',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('info_user', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('info_news', 'collected_counts')
    op.drop_table('author_register_info')
    # ### end Alembic commands ###
