"""empty message

Revision ID: 72ed609d3a10
Revises: 0ca1d3c5b27c
Create Date: 2021-08-02 18:38:09.071927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ed609d3a10'
down_revision = '0ca1d3c5b27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'remarks')
    # ### end Alembic commands ###
