"""empty message

Revision ID: 88dea72210b4
Revises: cbdd8d714a6f
Create Date: 2021-07-29 22:20:18.122937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88dea72210b4'
down_revision = 'cbdd8d714a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_register_info', sa.Column('take_ID_card_url', sa.String(length=256), nullable=True))
    op.drop_column('author_register_info', 'negative_ID_card_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_register_info', sa.Column('negative_ID_card_url', mysql.VARCHAR(collation='utf8_bin', length=256), nullable=True))
    op.drop_column('author_register_info', 'take_ID_card_url')
    # ### end Alembic commands ###
