"""empty message

Revision ID: cbdd8d714a6f
Revises: 587069022ff9
Create Date: 2021-07-29 22:01:35.702310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbdd8d714a6f'
down_revision = '587069022ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_register_info', 'index_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_register_info', sa.Column('index_image_url', mysql.VARCHAR(collation='utf8_bin', length=256), nullable=True))
    # ### end Alembic commands ###
